### PR TITLE
Add a config for primary-secondary component

### PR DESCRIPTION
**Pull request by saeedseyfi**

### CODE REVIEW

**Comment by parsipixel** [comment]
Barabim baraboom ;) 👍

**Comment by saeedseyfi** [comment]
@powerbuoy

**Comment by powerbuoy** [comment]
Cheers guys, however, I'd prefer if we could use the existing `$gutter-default`, or perhaps add a new `$gutter-large` (as you might want slightly more gutter between such large columns as opposed to a grid of images for example), something like:

**config/_layout.scss**

```
$gutter-large: 3rem;
$primary-content-width: 70%;
```

**components/_primary-secondary.scss**

```
.primary-content {
    width: calc(#{$primary-content-width} - #{$gutter-large / 2});
}

.secondary-content {
    width: calc(#{100% - $primary-content-width} - #{$gutter-large / 2});
}
```

What do you think?

**Comment by powerbuoy** [comment]
Went ahead and implemented this: https://github.com/powerbuoy/SleekCSS/blob/master/components/_primary-secondary.scss

**Comment by saeedseyfi** [comment]
I liked it, But using `calc` might be a bit risky according to browsers support: http://caniuse.com/#feat=calc

But that's ok 👍

**Comment by saeedseyfi** [comment]
I'll close the PR, thanks Ante ;)

**Comment by powerbuoy** [comment]
I use `calc` in several other places already. I've pretty much dropped support for non evergreen browsers.

**Pull request closed without merging**
